### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by Trott** [TheAlphaNerd/cascadia-talk#1]
Any chance I can convince you to put a license on this thing so I know exactly what I should do to feel guilt-free about stealing from it for my own slides?

**Comment by MylesBorins** [comment]
Absolutely!

**Comment by MylesBorins** [comment]
@Trott I have included the license information in the Readme and package.json. The copy for the licenses are also now included in the repo.

The software behind the talk is licensed MIT.

The content is licensed Creative Commons Attribution-ShareAlike 4.0 International Public License

**Comment by Trott** [comment]
Hooray! Thanks!
